### ISSUE TITLE
Didn't sync and removed all my settings

### ISSUE THREAD

**Issue by Sequoya42** [macor161/atom-package-sync#3]
Hello,

Your package did not work.
I had all my config on my mac, downloaded and signed in with google.
I downloaded your package on my linux and it did not import my config.
Coming back on my mac, my packages are still there, but my config aren't.
I've lost all my snippets etc.

**Comment by macor161** [comment]
Hello Raphael,

Really sorry about that. You're the first person who experience this issue. I will go check the database to see if I can recover your settings. Is it possible for you to send me your Atom logs? (Cmd+Opt+I and copy paste any error message). 

I will test the package on a mac tonight to see if I experience the same bug.

To help me find your lost settings, can you tell me what you had exactly in them? Any keymap or snippets?

**Comment by Sequoya42** [comment]
Thank you for helping.

Here's the log: 

```log
<embedded>:20553 Uncaught (in promise) Error: Failed to load package 'atom-package-sync'
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:664:37)
    at /Applications/Atom.app/Contents/Resources/app/src/package-manager.js:377:25
    at /Applications/Atom.app/Contents/Resources/app/src/config.js:644:26
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Config.module.exports.Config.emitChangeEvent (/Applications/Atom.app/Contents/Resources/app/src/config.js:835:35)
    at Config.module.exports.Config.setRawValue (/Applications/Atom.app/Contents/Resources/app/src/config.js:621:25)
    at Config.module.exports.Config.set (/Applications/Atom.app/Contents/Resources/app/src/config.js:236:20)
    at Config.module.exports.Config.removeAtKeyPath (/Applications/Atom.app/Contents/Resources/app/src/config.js:386:18)
    at PackageManager.module.exports.PackageManager.removePackageNameFromDisabledPackages (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:680:32)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:563:25
    at exit (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:128:22)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:338:17)
    at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:368:17)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```


For the snippets parts : 
I had something called `csl` [that was console.log something]
And something called `smod` [That was a snippet that expanded into : 

```js
const state = {};
const getters = {};
const actions = {};
const mutations = {};

export default {
  state,
  getters,
  actions,
  mutations
};

```

**Comment by macor161** [comment]
Thanks! Will look into it as soon as possible.

**Comment by Sequoya42** [comment]
Any news?

**Comment by macor161** [comment]
Sorry for the delay. I'm currently on vacation and have limited access to my tools. From what I see in the logs, the package doesn't seem to start at all on your computer due to an error. Can you tell me what version of Atom you are using on the computer you got the logs from?

**Comment by macor161** [comment]
I will be back next weekend and will be able to investigate more.

**Comment by Sequoya42** [comment]
Hello, 
Sorry for the delay, was in vacation too.

Unfortunately, I don't remember which atom version I was running, and I don't have the osx computer anymore.
[I downloaded your plugin to "migrate" everything to my linux, as I had to get rid of the osx].

On the linux, I don't even have basic config files anymore.
It's as if, your plugin "moved" the whole directory somewhere or something.

**Comment by Sequoya42** [comment]
Hello again,

I set up Atom on another mac, and used your package.

My .atom contained what a new Atom setup usually contains.
It installed all the packages, I still had those file in "normal state".

But when it finished, and I had the notification of "Package sync",
all the files were modified to contains something like :  
```# snippets file (not found)```

Regards,

**Comment by macor161** [comment]
Thanks for the info! I'm back from vacation so I will probably have the time to check this out tomorrow. 

Best regards,

**Comment by macor161** [comment]
Hello Raphael,

I'm really sorry that you lost your files. After reviewing the logs and tested the code extensively, I could not find any bug corresponding to your description unfortunately. Everything looks good on linux, mac and windows. Maybe it was caused by an especially old version of Atom or a filesystem problem. I will nevertheless continue investigating the bug in the coming days to see if something can be found.

Best regards,

**Comment by Sequoya42** [comment]
Hello,

I've been using many different computers [from osx to linux].
It seems the problem is [kindda] solved.

Might have been that old atom version.

Last time I commented, [12 days ago], after your package  cleared my .atom, I recreated it, and wrote my snippets etc again.

After that, it seemed to sync, as I used a different computer, logged in, and I had everything [snippets included].

Then some new snippets, and those one were not sync. 

Unfortunately, I don't remember if it syncs correctly between mac, and not linux or something.

Anyhow, I'm happy as it is, [maybe you can close the issue?]

Thank you very much for this plugin, it is a real life saver for me !

**Comment by macor161** [comment]
Glad you like the package! :+1: 
I will look at the snippets synchronization more specifically this weekend since the problem seems to be related to this part of the code.

Thanks again for your feedback. It is invaluable for helping me create a better product.
